[package]
name = "zancord-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "zancord-app"
path = "src/main.rs"

[[bin]]
name = "zancord-ui"
path = "src/bin/ui.rs"

[dependencies]
zancord-protocol = { workspace = true }
zancord-signaling-client = { path = "../zancord-signaling-client" }
zancord-audio = { path = "../zancord-audio" }
zancord-transport = { path = "../zancord-transport" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
slint = { workspace = true }
arboard = "3"

[build-dependencies]
slint-build = { workspace = true }
